services:
  - type: web
    name: invoice-generator-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
